/**
 * api/v1/index.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php;session_start () ;/DevelopmentErrorReportingif (!defined ('DEVELOPMENT_MODE') ) {error_reporting (E_ALL) ;ini_set ('display_errors',1) ;ini_set ('display_startup_errors',1) ;}declare (strict_types=1) ;;/***RESTfulAPIforPOLRESSamosir*Version1..
    0*//Enableerrorreportingfordebuggingerror_reporting (E_ALL) ;ini_set ('display_errors',1) ;/EnableCORSheader ("Access-Control-Allow-Origin:*") ;header ("Access-Control-Allow-Methods:GET,POST,PUT,DELETE,OPTIONS") ;header ("Access-Control-Allow-Headers:Content-Type,Authorization") ;/Handlepreflightrequestsif ($_SERVER'\1\'=>=='OPTIONS') {exit (0) ;}/Includedependenciesrequire_oncedirname (__DIR__,2) ..
    '/core/config.php';require_oncedirname (__DIR__,2) .'/core/auth_check..
    php';/APIResponseclassclassApiResponse{publicstaticfunctionsuccess ($data=null,$message='Success') {http_response_code (200) ;echojson_encode ('\1\'=>\2) ;exit;}publicstaticfunctionerror ($message,$code=400,$data=null) {http_response_code ($code) ;echojson_encode ('\1\'=>\2,'timestamp'=>date ('c') ]) ;exit;}publicstaticfunctionvalidation ($errors) {http_response_code (422) ;echojson_encode ('\1\'=>\2,'timestamp'=>date ('c') ]) ;exit;}}/DatabaseconnectionclassDatabase{privatestatic$pdo=null;publicstaticfunctiongetConnection () {if (self::$pdo===null) {try{self::$pdo=newPDO ("mysql:host="..
    DB_HOST.";dbname="..
    DB_NAME,DB_USER,DB_PASS) ;self::$pdo->setAttribute (PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION) ;self::$pdo->setAttribute (PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC) ;}catch (PDOException$e) {ApiResponse::error ('Databaseconnectionfailed:'..
    $e->getMessage () ,500) ;}}returnself::$pdo;}}/AuthenticationmiddlewareclassAuth{publicstaticfunctioncheck () {/Fornow,allowtestmodeif (isset (filter_input (INPUT_GET,'\1\',FILTER_DEFAULT) ) &&filter_input (INPUT_GET,'\1\',FILTER_DEFAULT) ==='true') {return'\1\'=>\2;}/Checksessionauthenticationif (!isset ($_SESSION['logged_in']) ||$_SESSION['logged_in']!==true) {ApiResponse::error ('Unauthorized',401) ;}return'\1\'=>\2??1,'username'=>$_SESSION['username']??'User'];}}/RequestvalidatorclassValidator{private$data;private$rules;private$errors=[];publicfunction__construct ($data,$rules=[]) {$this->data=$data;$this->rules=$rules;}publicfunctionrequired ($field) {if (!isset ($this->data[$field]) ||empty ($this->data[$field]) ) {$this->errors[$field][]="$fieldisrequired";}return$this;}publicfunctionstring ($field) {if (isset ($this->data[$field]) &&!is_string ($this->data[$field]) ) {$this->errors[$field][]="$fieldmustbeastring";}return$this;}publicfunctionmaxLength ($field,$length) {if (isset ($this->data[$field]) &&strlen ($this->data[$field]) >$length) {$this->errors[$field][]="$fieldmustnotexceed$lengthcharacters";}return$this;}publicfunctionisValid () {returnempty ($this->errors) ;}publicfunctiongetErrors () {return$this->errors;}}/Getrequestmethodandpath$method=$_SERVER['REQUEST_METHOD'];$path=parse_url ($_SERVER['REQUEST_URI'],PHP_URL_PATH) ;$path_parts=explode ('/',trim ($path,'/') ) ;/Debugerror_log ("Originalpath:$path") ;error_log ("Pathparts:"..
    print_r ($path_parts,true) ) ;/Remove'api'andversionfrompathif ($path_parts[0]==='api'&&isset ($path_parts[1]) &&$path_parts[1]==='v1') {$path_parts=array_slice ($path_parts,2) ;}$endpoint=implode ('/',$path_parts) ;$query_string=$_SERVER['QUERY_STRING'];/Routetherequestswitch ($endpoint) {/Authenticationendpointscase'auth/login':if ($method==='POST') {/Simpleloginfortesting$_SESSION'\1\'=>true;$_SESSION'\1\'=>'TestUser';$_SESSION'\1\'=>1;ApiResponse::success ('\1\'=>\2,'token'=>'test_token_'..
    time () ],'Loginsuccessful') ;}break;case'auth/logout':if ($method==='POST') {session_destroy () ;ApiResponse::success (null,'Logoutsuccessful') ;}break;case'auth/profile':if ($method==='GET') {$user=Auth::check () ;ApiResponse::success ($user) ;}break;/Bagianendpointscase'bagian':handleBagian ($method) ;break;case'bagian/'..
     ($path_parts[1]??'') :handleBagianDetail ($method,$path_parts[1]??null) ;break;/Personilendpointscase'personil':handlePersonil ($method) ;break;case'personil/'..
     ($path_parts[1]??'') :handlePersonilDetail ($method,$path_parts[1]??null) ;break;/Statisticsendpointscase'stats/bagian':if ($method==='GET') {handleStatsBagian () ;}break;case'stats/personil':if ($method==='GET') {handleStatsPersonil () ;}break;case'stats/pangkat':if ($method==='GET') {handleStatsPangkat () ;}break;default:ApiResponse::error ('Endpointnotfound',404) ;}/BagianhandlersfunctionhandleBagian ($method) {$db=Database::getConnection () ;switch ($method) {case'GET':/Getallbagian$stmt=$db->query ("SELECTb..
    *, (SELECTCOUNT (*) FROMpersonilWHEREbagian_id=b.id) aspersonil_countFROMbagianbORDERBYb..
    nama_bagian") ;$bagian=$stmt->fetchAll () ;ApiResponse::success ($bagian) ;case'POST':/CreatenewbagianAuth::check () ;$data=json_decode (file_get_contents ('php://input') ,true) ;$validator=newValidator ($data) ;$validator->required ('nama_bagian') ->string ('nama_bagian') ->maxLength ('nama_bagian',255) ;if (!$validator->isValid () ) {ApiResponse::validation ($validator->getErrors () ) ;}try{$stmt=$db->prepare ("INSERTINTObagian (nama_bagian,type) VALUES (?,'BAG/SAT/SIE') ") ;$stmt->execute ([$data['nama_bagian']]) ;$bagianId=$db->lastInsertId () ;/Getcreatedbagian$stmt=$db->prepare ("SELECT*FROMbagianWHEREid=?") ;$stmt->execute ([$bagianId]) ;$bagian=$stmt->fetch () ;ApiResponse::success ($bagian,'Bagiancreatedsuccessfully') ;}catch (PDOException$e) {ApiResponse::error ('Failedtocreatebagian:'..
    $e->getMessage () ,500) ;}default:ApiResponse::error ('Methodnotallowed',405) ;}}functionhandleBagianDetail ($method,$id) {if (!$id) {ApiResponse::error ('BagianIDisrequired',400) ;}$db=Database::getConnection () ;switch ($method) {case'GET':$stmt=$db->prepare ("SELECT*FROMbagianWHEREid=?") ;$stmt->execute ([$id]) ;$bagian=$stmt->fetch () ;if (!$bagian) {ApiResponse::error ('Bagiannotfound',404) ;}ApiResponse::success ($bagian) ;case'PUT':Auth::check () ;$data=json_decode (file_get_contents ('php://input') ,true) ;$validator=newValidator ($data) ;$validator->required ('nama_bagian') ->string ('nama_bagian') ->maxLength ('nama_bagat',255) ;if (!$validator->isValid () ) {ApiResponse::validation ($validator->getErrors () ) ;}try{$stmt=$db->prepare ("UPDATEbagianSETnama_bagian=?WHEREid=?") ;$stmt->execute ([$data['nama_bagian'],$id]) ;if ($stmt->rowCount () ===0) {ApiResponse::error ('Bagiannotfound',404) ;}/Getupdatedbagian$stmt=$db->prepare ("SELECT*FROMbagianWHEREid=?") ;$stmt->execute ([$id]) ;$bagian=$stmt->fetch () ;ApiResponse::success ($bagian,'Bagianupdatedsuccessfully') ;}catch (PDOException$e) {ApiResponse::error ('Failedtoupdatebagian:'..
    $e->getMessage () ,500) ;}case'DELETE':Auth::check () ;/Checkifbagianhaspersonil$stmt=$db->prepare ("SELECTCOUNT (*) FROMpersonilWHEREbagian_id=?") ;$stmt->execute ([$id]) ;$personilCount=$stmt->fetchColumn () ;if ($personilCount>0) {ApiResponse::error ('Cannotdeletebagianwithexistingpersonil',400) ;}try{$stmt=$db->prepare ("DELETEFROMbagianWHEREid=?") ;$stmt->execute ([$id]) ;if ($stmt->rowCount () ===0) {ApiResponse::error ('Bagiannotfound',404) ;}ApiResponse::success (null,'Bagiandeletedsuccessfully') ;}catch (PDOException$e) {ApiResponse::error ('Failedtodeletebagian:'..
    $e->getMessage () ,500) ;}default:ApiResponse::error ('Methodnotallowed',405) ;}}/PersonilhandlersfunctionhandlePersonil ($method) {$db=Database::getConnection () ;switch ($method) {case'GET':$page=isset (filter_input (INPUT_GET,'\1\',FILTER_DEFAULT) ) ? (int) filter_input (INPUT_GET,'\1\',FILTER_DEFAULT) :1;$limit=isset (filter_input (INPUT_GET,'\1\',FILTER_DEFAULT) ) ? (int) filter_input (INPUT_GET,'\1\',FILTER_DEFAULT) :50;$offset= ($page-1) *$limit;/Gettotalcount$stmt=$db->query ("SELECTCOUNT (*) astotalFROMpersonil") ;$total=$stmt->fetch () ['total'];/Getpersonilwithjoins$stmt=$db->query ("SELECTp..
    id,p.nama,p.nrp,p.status_ket,p.status_kepegawaian,pg.nama_pangkat,pg.singkatan,pg..
    level_pangkat,j.nama_jabatan,b.nama_bagianFROMpersonilpJOINpangkatpgONp.pangkat_id=pg..
    idJOINjabatanjONp.jabatan_id=j.idLEFTJOINbagianbONp.bagian_id=b.idORDERBYCASEWHENpg..
    level_pangkatISnullTHEN999999ELSEpg.level_pangkatENDASC,CASEWHENp..
    nrpREGEXP'^[0-9]{8}'THENCASEWHENSUBSTRING (p.nrp,1,1) ='0'THENCONCAT ('20',SUBSTRING (p..
    nrp,1,4) ) ELSECONCAT ('19',SUBSTRING (p.nrp,1,4) ) ENDWHENp..
    nrpREGEXP'^[0-9]{9}'THENCONCAT ('19',SUBSTRING (p.nrp,1,6) ) ELSE'99999999'ENDASC,p..
    namaLIMIT$limitOFFSET$offset") ;$personil=$stmt->fetchAll () ;ApiResponse::success ('\1\'=>\2]) ;default:ApiResponse::error ('Methodnotallowed',405) ;}}functionhandlePersonilDetail ($method,$id) {if (!$id) {ApiResponse::error ('PersonilIDisrequired',400) ;}$db=Database::getConnection () ;switch ($method) {case'GET':$stmt=$db->prepare ("SELECTp..
    *,pg.nama_pangkat,pg.singkatan,j.nama_jabatan,b.nama_bagianFROMpersonilpJOINpangkatpgONp..
    pangkat_id=pg.idJOINjabatanjONp.jabatan_id=j.idLEFTJOINbagianbONp.bagian_id=b.idWHEREp..
    id=?") ;$stmt->execute ([$id]) ;$personil=$stmt->fetch () ;if (!$personil) {ApiResponse::error ('Personilnotfound',404) ;}ApiResponse::success ($personil) ;default:ApiResponse::error ('Methodnotallowed',405) ;}}/StatisticshandlersfunctionhandleStatsBagian () {$db=Database::getConnection () ;$stmt=$db->query ("SELECTCOUNT (*) astotal_bagian,COUNT (CASEWHENtype='BAG/SAT/SIE'THEN1END) asbag_sat_sie,COUNT (CASEWHENtypeLIKE'%POLSEK%'THEN1END) aspolsekFROMbagian") ;$stats=$stmt->fetch () ;ApiResponse::success ($stats) ;}functionhandleStatsPersonil () {$db=Database::getConnection () ;$stmt=$db->query ("SELECTCOUNT (*) astotal_personil,COUNT (CASEWHENstatus_kepegawaian='POLRI'THEN1END) aspolri,COUNT (CASEWHENstatus_kepegawaian='ASN'THEN1END) asasn,COUNT (CASEWHENstatus_kepegawaian='P3K'THEN1END) asp3k,COUNT (CASEWHENstatus_ket='aktif'THEN1END) asaktifFROMpersonil") ;$stats=$stmt->fetch () ;ApiResponse::success ($stats) ;}functionhandleStatsPangkat () {$db=Database::getConnection () ;$stmt=$db->query ("SELECTpg..
    nama_pangkat,pg.singkatan,COUNT (p.id) asjumlah,ROUND (COUNT (p.id) *100..
    0/ (SELECTCOUNT (*) FROMpersonil) ,2) aspersenFROMpangkatpgLEFTJOINpersonilpONpg.id=p..
    pangkat_idGROUPBYpg.id,pg.nama_pangkat,pg.singkatanHAVINGCOUNT (p.id) >0ORDERBYCOUNT (p..
    id) DESC") ;$stats=$stmt->fetchAll () ;ApiResponse::success ($stats) ;}?>.
