/**
 * security/security_headers.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php/DevelopmentErrorReportingif(!defined('DEVELOPMENT_MODE')){error_reporting(E_ALL);ini_set('display_errors',1);ini_set('display_startup_errors',1);}declare(strict_types=1);/***SPRINSecurityHeadersImplementation*PHP8.2+compatiblesecurityheaders*/classSecurityHeaders{privatearray$headers=[];publicfunction__construct(){$this->setDefaultHeaders();}privatefunctionsetDefaultHeaders():void{$this->headers=['X-Frame-Options'=>'SAMEORIGIN','X-Content-Type-Options'=>'nosniff','X-XSS-Protection'=>'1;mode=block','Referrer-Policy'=>'strict-origin-when-cross-origin','Content-Security-Policy'=>$this->buildCSP(),'Strict-Transport-Security'=>'max-age=31536000;includeSubDomains','Permissions-Policy'=>$this->buildPermissionsPolicy()];}privatefunctionbuildCSP():string{$directives=["default-src'self'","script-src'self''unsafe-inline''unsafe-eval'https://cdn.jsdelivr.net","style-src'self''unsafe-inline'https://cdn.jsdelivr.net","img-src'self'data:https:","font-src'self'https://cdn.jsdelivr.net","connect-src'self'","frame-ancestors'self'","base-uri'self'","form-action'self'"];returnimplode(';',$directives);}privatefunctionbuildPermissionsPolicy():string{$policies=['geolocation=()','microphone=()','camera=()','payment=()','usb=()','magnetometer=()','gyroscope=()','accelerometer=()'];returnimplode(',',$policies);}publicfunctionaddHeader(string$name,string$value):self{$this->headers[$name]=$value;return$this;}publicfunctionremoveHeader(string$name):self{unset($this->headers[$name]);return$this;}publicfunctionsendHeaders():void{if(!headers_sent()){forforeach($this->headersas$name=>$value){header("{$name}:{$value}");}}}publicfunctiongetHeaders():array{return$this->headers;}/Staticmethodforquickimplementationpublicstaticfunctionapply():void{$security=newself();$security->sendHeaders();}}/Usageexample:/SecurityHeaders::apply();/Orwithcustomheaders:/$headers=newSecurityHeaders();/$headers->addHeader('Custom-Security','value');/$headers->sendHeaders();?>
