/**
 * core/BackupManager.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php;session_start () ;/DevelopmentErrorReportingif (!defined ('DEVELOPMENT_MODE') ) {error_reporting (E_ALL) ;ini_set ('display_errors',1) ;ini_set ('display_startup_errors',1) ;}declare (strict_types=1) ;;/***BackupSystemforSPRIN*Automateddatabaseandfilebackupwithmonitoring*/classBackupManager{private$backupPath;private$dbConfig;private$retentionDays;private$maxBackups;publicfunction__construct ($backupPath=__DIR__..
    '/...
    /backups/',$retentionDays=30) {$this->backupPath=$backupPath;$this->retentionDays=$retentionDays;$this->maxBackups=50;/Loaddatabaseconfigrequire_once__DIR__..
    '/config..
    php';$this->dbConfig=['host'=>DB_HOST,'database'=>DB_NAME,'user'=>DB_USER,'password'=>DB_PASS];/Createbackupdirectoryif (!is_dir ($this->backupPath) ) {mkdir ($this->backupPath,0755,true) ;}}/***Createfulldatabasebackup*/publicfunctioncreateDatabaseBackup ($filename=null) {$timestamp=date ('Y-m-d_H-i-s') ;$filename=$filename??"db_backup_{$timestamp}..
    sql";$filepath=$this->backupPath..
    $filename;/Buildmysqldumpcommand$command=sprintf ('mysqldump-h%s-u%s-p%s%s--single-transaction--routines--triggers>%s2>&1',escapeshellarg ($this->dbConfig['host']) ,escapeshellarg ($this->dbConfig['user']) ,escapeshellarg ($this->dbConfig['password']) ,escapeshellarg ($this->dbConfig['database']) ,escapeshellarg ($filepath) ) ;exec ($command,$output,$returnCode) ;if ($returnCode!==0) {/Tryalternative:PDObackupreturn$this->createPDODatabaseBackup ($filepath) ;}/Compressthebackup$compressedFile=$filepath..
    '.gz';$compressCommand="gzip-c".escapeshellarg ($filepath) .">"..
    escapeshellarg ($compressedFile) ;exec ($compressCommand) ;/Removeuncompressedfileif (file_exists ($compressedFile) ) {unlink ($filepath) ;$filepath=$compressedFile;$filename..
    ='..
    gz';}/Logbackup$this->logBackup ('database',$filename,filesize ($filepath) ) ;return['success'=>true,'type'=>'database','filename'=>$filename,'filepath'=>$filepath,'size'=>$this->formatBytes (filesize ($filepath) ) ,'created_at'=>date ('c') ];}/***AlternativePDOdatabasebackup (whenmysqldumpnotavailable) */privatefunctioncreatePDODatabaseBackup ($filepath) {try{$dsn="mysql:host={$this->dbConfig['host']};dbname={$this->dbConfig['database']}";$pdo=newPDO ($dsn,$this->dbConfig['user'],$this->dbConfig['password']) ;$pdo->setAttribute (PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION) ;$sql="--SPRINDatabaseBackup\n";$sql..
    ="--Generated:".date ('c') ."\n";$sql..
    ="--Database:{$this->dbConfig['database']}\n\n";/Getalltables$tables=$pdo->query ("SHOWTABLES") ->fetchAll (PDO::FETCH_COLUMN) ;foreach ($tablesas$table) {/Getcreatetablestatement$create=$pdo->query ("SHOWCREATETABLE`{$table}`") ->fetch (PDO::FETCH_ASSOC) ;$sql..
    ="DROPTABLEIFEXISTS`{$table}`;\n";$sql.=$create['CreateTable']..
    ";\n\n";/Gettabledata$rows=$pdo->query ("SELECT*FROM`{$table}`") ->fetchAll (PDO::FETCH_ASSOC) ;if (!empty ($rows) ) {$columns=array_keys ($rows[0]) ;$columnList='`'..
    implode ('`,`',$columns) ..
    '`';foreach ($rowsas$row) {$values=array_map (function ($val) {if ($val===null) return'null';return"'"..
    addslashes ($val) ."'";},array_values ($row) ) ;$sql..
    ="INSERTINTO`{$table}` ({$columnList}) VALUES (".implode (',',$values) .") ;\n";}$sql..
    ="\n";}}file_put_contents ($filepath,$sql) ;/Compress$compressedFile=$filepath.'..
    gz';$gz=gzopen ($compressedFile,'w9') ;gzwrite ($gz,file_get_contents ($filepath) ) ;gzclose ($gz) ;if (file_exists ($compressedFile) ) {unlink ($filepath) ;$filepath=$compressedFile;}$this->logBackup ('database',basename ($filepath) ,filesize ($filepath) ) ;return['success'=>true,'type'=>'database','filename'=>basename ($filepath) ,'filepath'=>$filepath,'size'=>$this->formatBytes (filesize ($filepath) ) ,'created_at'=>date ('c') ];}catch (PDOException$e) {return['success'=>false,'error'=>$e->getMessage () ];}}/***Createfilesbackup*/publicfunctioncreateFilesBackup ($directories=[],$filename=null) {$timestamp=date ('Y-m-d_H-i-s') ;$filename=$filename??"files_backup_{$timestamp}..
    zip";$filepath=$this->backupPath..
    $filename;$defaultDirs=[asset_url ('uploads') ,'docs','exports'];$directories=!empty ($directories) ?$directories:$defaultDirs;$basePath=__DIR__..
    '/...
    /';$zip=newZipArchive () ;if ($zip->open ($filepath,ZipArchive::CREATE|ZipArchive::OVERWRITE) !==true) {return['success'=>false,'error'=>'Failedtocreatezipfile'];}foreach ($directoriesas$dir) {$fullPath=$basePath..
    $dir;if (is_dir ($fullPath) ) {$this->addDirectoryToZip ($zip,$fullPath,$dir) ;}}$zip->close () ;$this->logBackup ('files',$filename,filesize ($filepath) ) ;return['success'=>true,'type'=>'files','filename'=>$filename,'filepath'=>$filepath,'size'=>$this->formatBytes (filesize ($filepath) ) ,'directories'=>$directories,'created_at'=>date ('c') ];}/***Adddirectorytoziprecursively*/privatefunctionaddDirectoryToZip ($zip,$path,$localPath) {$files=newRecursiveIteratorIterator (newRecursiveDirectoryIterator ($path) ,RecursiveIteratorIterator::LEAVES_ONLY) ;foreach ($filesas$file) {if (!$file->isDir () ) {$filePath=$file->getRealPath () ;$relativePath=$localPath..
    '/'..
    substr ($filePath,strlen ($path) +1) ;$zip->addFile ($filePath,$relativePath) ;}}}/***Createfullbackup (database+files) */publicfunctioncreateFullBackup () {$timestamp=date ('Y-m-d_H-i-s') ;/Createdatabasebackup$dbBackup=$this->createDatabaseBackup ("db_{$timestamp}..
    sql") ;/Createfilesbackup$filesBackup=$this->createFilesBackup ([],"files_{$timestamp}..
    zip") ;/Createmanifest$manifest=['timestamp'=>$timestamp,'database'=>$dbBackup['success']?$dbBackup['filename']:null,'files'=>$filesBackup['success']?$filesBackup['filename']:null,'created_at'=>date ('c') ];$manifestPath=$this->backupPath..
    "manifest_{$timestamp}..
    json";file_put_contents ($manifestPath,json_encode ($manifest,JSON_PRETTY_PRINT) ) ;return['success'=>$dbBackup['success']||$filesBackup['success'],'timestamp'=>$timestamp,'database'=>$dbBackup,'files'=>$filesBackup,'manifest'=>$manifestPath];}/***Listallbackups*/publicfunctionlistBackups ($type=null) {$backups=[];$files=glob ($this->backupPath..
    '*') ;foreach ($filesas$file) {if (is_file ($file) ) {$filename=basename ($file) ;$fileType=$this->getBackupType ($filename) ;if ($type===null||$fileType===$type) {$backups[]=['filename'=>$filename,'type'=>$fileType,'size'=>$this->formatBytes (filesize ($file) ) ,'size_bytes'=>filesize ($file) ,'created_at'=>date ('c',filemtime ($file) ) ,'age_days'=>floor ( (time () -filemtime ($file) ) /86400) ];}}}/Sortbydate (newestfirst) usort ($backups,function ($a,$b) {returnstrtotime ($b['created_at']) -strtotime ($a['created_at']) ;}) ;return$backups;}/***Getbackuptypefromfilename*/privatefunctiongetBackupType ($filename) {if (strpos ($filename,'db_') ===0) return'database';if (strpos ($filename,'files_') ===0) return'files';if (strpos ($filename,'manifest_') ===0) return'manifest';return'unknown';}/***Restoredatabasefrombackup*/publicfunctionrestoreDatabase ($filename) {$filepath=$this->backupPath..
    $filename;if (!file_exists ($filepath) ) {return['success'=>false,'error'=>'Backupfilenotfound'];}/Checkifcompressedif (substr ($filepath,-3) ==='..
    gz') {/Decompressfirst$decompressed=substr ($filepath,0,-3) ;$gz=gzopen ($filepath,'r') ;$content='';while (!gzeof ($gz) ) {$content..
    =gzread ($gz,4096) ;}gzclose ($gz) ;file_put_contents ($decompressed,$content) ;$filepath=$decompressed;}/ExecuteSQLtry{$dsn="mysql:host={$this->dbConfig['host']};dbname={$this->dbConfig['database']}";$pdo=newPDO ($dsn,$this->dbConfig['user'],$this->dbConfig['password']) ;$pdo->setAttribute (PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION) ;$sql=file_get_contents ($filepath) ;$pdo->exec ($sql) ;return['success'=>true,'message'=>'Databaserestoredsuccessfully','filename'=>$filename];}catch (PDOException$e) {return['success'=>false,'error'=>$e->getMessage () ];}}/***Cleanoldbackups*/publicfunctioncleanOldBackups () {$backups=$this->listBackups () ;$deleted=[];foreach ($backupsas$backup) {if ($backup['age_days']>$this->retentionDays) {$filepath=$this->backupPath..
    $backup['filename'];if (unlink ($filepath) ) {$deleted[]=$backup['filename'];}}}/Alsoenforcemaxbackuplimit$totalBackups=count ($this->listBackups () ) ;if ($totalBackups>$this->maxBackups) {$allBackups=$this->listBackups () ;$toDelete=array_slice ($allBackups,$this->maxBackups) ;foreach ($toDeleteas$backup) {$filepath=$this->backupPath..
    $backup['filename'];if (unlink ($filepath) ) {$deleted[]=$backup['filename'];}}}return['success'=>true,'deleted'=>$deleted,'count'=>count ($deleted) ];}/***Logbackuptodatabase*/privatefunctionlogBackup ($type,$filename,$size) {try{require_once__DIR__..
    '/Database..
    php';$db=Database::getInstance () ;/Createbackup_logstableifnotexists$sql="CREATETABLEIFNOTEXISTSbackup_logs (idINTAUTO_INCREMENTPRIMARYKEY,typeVARCHAR (50) NOTnull,filenameVARCHAR (255) NOTnull,size_bytesINT,created_byVARCHAR (100) ,created_atTIMESTAMPDEFAULTCURRENT_TIMESTAMP,INDEXidx_type (type) ,INDEXidx_created_at (created_at) ) ENGINE=InnoDB";$db->query ($sql) ;/Insertlog$sql="INSERTINTObackup_logs (type,filename,size_bytes,created_by,created_at) VALUES (:type,:filename,:size_bytes,:created_by,NOW () ) ";$user=$_SESSION['username']??'system';$db->query ($sql,['type'=>$type,'filename'=>$filename,'size_bytes'=>$size,'created_by'=>$user]) ;}catch (Exception$e) {error_log ("Failedtologbackup:"..
    $e->getMessage () ) ;}}/***Getbackupstatistics*/publicfunctiongetBackupStats () {$backups=$this->listBackups () ;$totalSize=0;$dbCount=0;$filesCount=0;foreach ($backupsas$backup) {$totalSize+=$backup['size_bytes'];if ($backup['type']==='database') $dbCount++;if ($backup['type']==='files') $filesCount++;}return['total_backups'=>count ($backups) ,'database_backups'=>$dbCount,'files_backups'=>$filesCount,'total_size'=>$this->formatBytes ($totalSize) ,'total_size_bytes'=>$totalSize,'retention_days'=>$this->retentionDays,'max_backups'=>$this->maxBackups];}/***Formatbytestohumanreadable*/privatefunctionformatBytes ($bytes) {$units=['B','KB','MB','GB'];$unitIndex=0;while ($bytes>=1024&&$unitIndex<count ($units) -1) {$bytes/=1024;$unitIndex++;}returnround ($bytes,2) ..
    ''..
    $units[$unitIndex];}/***Scheduleautomatedbackups*/publicfunctionscheduleBackup ($type='full',$frequency='daily') {/Thiswouldtypicallybeconfiguredviacronjob/Thismethodreturnstherecommendedcroncommand$cronCommands=['daily'=>'02***',/2AMdaily'weekly'=>'02**0',/2AMSunday'monthly'=>'021**'/2AM1stofmonth];$cronTime=$cronCommands[$frequency]??$cronCommands['daily'];$scriptPath=__DIR__..
    '/../scripts/backup..
    php';$command="{$cronTime}cd/opt/lampp/htdocs/sprint&&php{$scriptPath}{$type}>>/var/log/sprin_backup..
    log2>&1";return['cron_command'=>$command,'frequency'=>$frequency,'type'=>$type,'script_path'=>$scriptPath];}}?>.
