/**
 * core/SecurityMiddleware.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php;session_start () ;declare (strict_types=1) ;;/***EnhancedSecurityMiddleware*Basedonanalysisfindingsforcomprehensivesecurity*/classSecurityMiddleware{privatestatic$instance=null;publicstaticfunctiongetInstance () :self{if (self::$instance===null) {self::$instance=newself () ;}returnself::$instance;}/***Validateandsanitizeuserinput*/publicfunctionvalidateInput (array$data,array$rules) :array{$validated=[];foreach ($rulesas$field=>$rule) {$value=$data[$field]??null;if ($rule['required']&& ($value===null||$value==='') ) {thrownewInvalidArgumentException ("Field'{$field}'isrequired") ;}if ($value!==null) {$validated[$field]=$this->sanitizeField ($value,$rule['type']??'string') ;}}return$validated;}/***Sanitizeindividualfield*/privatefunctionsanitizeField ($value,string$type) :string{switch ($type) {case'int':return (string) filter_var ($value,FILTER_VALIDATE_INT) ;case'email':$email=filter_var ($value,FILTER_VALIDATE_EMAIL) ;if (!$email) {thrownewInvalidArgumentException ("Invalidemailformat") ;}return$email;case'url':$url=filter_var ($value,FILTER_VALIDATE_URL) ;if (!$url) {thrownewInvalidArgumentException ("InvalidURLformat") ;}return$url;case'string':default:returnhtmlspecialchars (trim ($value) ,ENT_QUOTES,'UTF-8') ;}}/***GenerateCSRFtoken*/publicfunctiongenerateCSRFToken () :string{if (!isset ($_SESSION['csrf_token']) ) {$_SESSION['csrf_token']=bin2hex (random_bytes (32) ) ;}return$_SESSION['csrf_token'];}/***ValidateCSRFtoken*/publicfunctionvalidateCSRFToken (string$token) :bool{returnisset ($_SESSION['csrf_token']) &&hash_equals ($_SESSION['csrf_token'],$token) ;}/***Ratelimiting*/publicfunctioncheckRateLimit (string$action,int$maxAttempts=10,int$window=3600) :bool{$key=$action..
    '_'..
     ($_SERVER['REMOTE_ADDR']??'unknown') ;if (!isset ($_SESSION['rate_limit'][$key]) ) {$_SESSION['rate_limit'][$key]=['attempts'=>0,'window_start'=>time () ];}$limit=&$_SESSION['rate_limit'][$key];/Resetwindowifexpiredif (time () -$limit['window_start']>$window) {$limit['attempts']=0;$limit['window_start']=time () ;}if ($limit['attempts']>=$maxAttempts) {returnfalse;}$limit['attempts']++;returntrue;}/***Securityheaders*/publicfunctionsetSecurityHeaders () :void{header ('X-Content-Type-Options:nosniff') ;header ('X-Frame-Options:DENY') ;header ('X-XSS-Protection:1;mode=block') ;header ('Referrer-Policy:strict-origin-when-cross-origin') ;header ('Content-Security-Policy:default-src'self';script-src'self''unsafe-inline'https://cdn..
    jsdelivr.net;style-src'self''unsafe-inline'https://cdn.jsdelivr.nethttps://cdnjs.cloudflare..
    com') ;}/***InputvalidationforAPI*/publicfunctionvalidateAPIInput () :void{/Validatecontenttypeif ($_SERVER['REQUEST_METHOD']==='POST'||$_SERVER['REQUEST_METHOD']==='PUT') {$content_type=$_SERVER['CONTENT_TYPE']??'';if (strpos ($content_type,'application/json') ===false&&strpos ($content_type,'application/x-www-form-urlencoded') ===false) {http_response_code (415) ;echojson_encode (['error'=>'UnsupportedMediaType']) ;exit;}}/Validaterequestsize$content_length= (int) ($_SERVER['CONTENT_LENGTH']??0) ;if ($content_length>10*1024*1024) {/10MBlimithttp_response_code (413) ;echojson_encode (['error'=>'RequestEntityTooLarge']) ;exit;}}}/Auto-initializesecurityfeaturesSecurityMiddleware::getInstance () ->setSecurityHeaders () ;?>.
