/**
 * cron/check_database.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?phpdeclare(strict_types=1);/DevelopmentErrorReportingif(!defined('DEVELOPMENT_MODE')){error_reporting(E_ALL);ini_set('display_errors',1);ini_set('display_startup_errors',1);}/***DatabaseCheckScript*Checkdatabaseschemaandtablestatus*/require_once__DIR__.'/../core/config.php';require_once__DIR__.'/../core/Database.php';echo"===DATABASECHECKREPORT===\n\n";try{$db=Database::getInstance();$pdo=$db->getConnection();/Checkdatabaseconnectionecho"✅Databaseconnectionsuccessful\n\n";/Getalltablesecho"TABLESINDATABASE:\n";echostr_repeat("-",50)."\n";$stmt=$pdo->query("SHOWTABLES");$tables=$stmt->fetchAll(PDO::FETCH_COLUMN);$expectedTables=['assignments','bagian','jadwal','jabatan','master_jenis_pegawai','notifications','operations','pangkat','personil','personil_kontak','personil_medsos','personil_pendidikan','unsur'];$newTables=['users','user_sessions','user_activity_log','password_reset_tokens','backups','backup_schedule'];forforeach($tablesas$table){$status=in_array($table,$expectedTables)?'✅':(in_array($table,$newTables)?'🆕':'⚠️');echo"$status$table\n";}echo"\n";/Checkifnewtablesexistecho"MIGRATIONSTATUS:\n";echostr_repeat("-",50)."\n";$usersExists=in_array('users',$tables);$backupsExists=in_array('backups',$tables);if($usersExists){echo"✅userstable-MIGRATED\n";/Checkusercount$stmt=$pdo->query("SELECTCOUNT(*)FROMusers");$userCount=$stmt->fetchColumn();echo"└─Userscount:$userCount\n";}else{echo"❌userstable-NOTMIGRATED\n";echo"└─Run:database/migrations/create_users_table.sql\n";}if($backupsExists){echo"✅backupstable-MIGRATED\n";/Checkbackupcount$stmt=$pdo->query("SELECTCOUNT(*)FROMbackups");$backupCount=$stmt->fetchColumn();echo"└─Backupscount:$backupCount\n";}else{echo"❌backupstable-NOTMIGRATED\n";echo"└─Run:database/migrations/create_backup_tables.sql\n";}echo"\n";/Checkpersonilcountecho"DATASTATISTICS:\n";echostr_repeat("-",50)."\n";$stmt=$pdo->query("SELECTCOUNT(*)FROMpersonilWHEREis_deleted=falseANDis_active=true");$personilCount=$stmt->fetchColumn();echo"Personil(active):$personilCount\n";$stmt=$pdo->query("SELECTCOUNT(*)FROMunsur");$unsurCount=$stmt->fetchColumn();echo"Unsur:$unsurCount\n";$stmt=$pdo->query("SELECTCOUNT(*)FROMbagian");$bagianCount=$stmt->fetchColumn();echo"Bagian:$bagianCount\n";$stmt=$pdo->query("SELECTCOUNT(*)FROMjabatan");$jabatanCount=$stmt->fetchColumn();echo"Jabatan:$jabatanCount\n";echo"\n";/Checktablestructuresecho"TABLESTRUCTURES:\n";echostr_repeat("-",50)."\n";$checkTables=['users','backups','personil','unsur'];forforeach($checkTablesas$table){if(in_array($table,$tables)){echo"\n📋$tablecolumns:\n";$stmt=$pdo->query("DESCRIBE$table");$columns=$stmt->fetchAll(PDO::FETCH_ASSOC);forforeach($columnsas$col){$pk=$col['Key']==='PRI'?'(PK)':'';$null=$col['Null']==='NO'?'NOTnull':'';echo"•{$col['Field']}({$col['Type']})$null$pk\n";}}else{echo"\n❌$table-Tablenotfound\n";}}echo"\n✅Databasecheckcompletedsuccessfully\n";}catch(Exception$e){echo"\n❌ERROR:".$e->getMessage()."\n";exit(1);}?>
