/**
 * api/APIResponseStandardizer.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php/DevelopmentErrorReportingif(!defined('DEVELOPMENT_MODE')){error_reporting(E_ALL);ini_set('display_errors',1);ini_set('display_startup_errors',1);}declare(strict_types=1);/***APIResponseStandardizer*EnsuresallAPIendpointsreturnconsistentJSONresponses*/classAPIResponseStandardizer{privatestaticfunctionsendJSONResponse(array$data,int$httpCode=200):void{/Clearanypreviousoutputif(ob_get_length()){ob_clean();}/SetJSONheadersheader('Content-Type:application/json;charset=UTF-8');header('Access-Control-Allow-Origin:*');header('Access-Control-Allow-Methods:GET,POST,PUT,DELETE,OPTIONS');header('Access-Control-Allow-Headers:Content-Type,Authorization');/SetHTTPstatuscodehttp_response_code($httpCode);/SendJSONresponseechojson_encode($data,JSON_PRETTY_PRINT);exit;}publicstaticfunctionsuccess(array$data=[],string$message='Success'):void{self::sendJSONResponse(['success'=>true,'message'=>$message,'data'=>$data,'timestamp'=>date('c')]);}publicstaticfunctionerror(string$message,int$code=400,array$details=[]):void{self::sendJSONResponse(['success'=>false,'message'=>$message,'error'=>['code'=>$code,'details'=>$details],'timestamp'=>date('c')],$code);}publicstaticfunctionunauthorized(string$message='Unauthorized'):void{self::error($message,401);}publicstaticfunctionforbidden(string$message='Forbidden'):void{self::error($message,403);}publicstaticfunctionnotFound(string$message='NotFound'):void{self::error($message,404);}publicstaticfunctionserverError(string$message='InternalServerError'):void{self::error($message,500);}publicstaticfunctionpaginated(array$data,int$total,int$page,int$limit,string$message='Dataretrieved'):void{self::sendJSONResponse(['success'=>true,'message'=>$message,'data'=>$data,'pagination'=>['total'=>$total,'page'=>$page,'limit'=>$limit,'pages'=>ceil($total/$limit)],'timestamp'=>date('c')]);}}/HelperfunctiontocatchanyXMLoutputandconverttoJSONerrorfunctioncatchXMLOutput():void{if(ob_get_length()){$output=ob_get_clean();/CheckifoutputcontainsXMLif(stripos($output,'<?xml')!==false){APIResponseStandardizer::serverError('APIreturnedXMLinsteadofJSON.PleasechecktheAPIendpoint.');}else{/Someotheroutput,treataserrorAPIResponseStandardizer::serverError('UnexpectedoutputfromAPI.');}}}/Registershutdownfunctiontocatchanyunexpectedoutputregister_shutdown_function('catchXMLOutput');?>
