/**
 * api/calendar_api.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php/DevelopmentErrorReportingif(!defined('DEVELOPMENT_MODE')){error_reporting(E_ALL);ini_set('display_errors',1);ini_set('display_startup_errors',1);}declare(strict_types=1);/***CalendarAPI-SimpleScheduleStatistics*/require_once__DIR__.'/../core/config.php';require_once__DIR__.'/../core/Database.php';require_once__DIR__.'/../core/SessionManager.php';require_once__DIR__.'/../core/auth_helper.php';/InitializesessionSessionManager::start();/Setheadersheader("Content-Type:application/json;charset=UTF-8");header("Access-Control-Allow-Origin:*");/Disableerrordisplayinproductionif(ENVIRONMENT!=='development'){error_reporting(0);ini_set('display_errors',0);}/CheckauthenticationusingAuthHelperif(!AuthHelper::validateSession()){http_response_code(401);echojson_encode('\1\'=>\2);exit;}try{/UseDatabasesingleton$db=Database::getInstance();$pdo=$db->getConnection();/Getactionparameter$action=isset(filter_input(INPUT_GET,'\1\',FILTER_DEFAULT))?filter_input(INPUT_GET,'\1\',FILTER_DEFAULT):'getStats';switch($action){case'getStats':/Getschedulestatistics$today=date('Y-m-d');$week_end=date('Y-m-d',strtotime('+7days'));/Trytogetscheduledatafromjadwaltabletry{/Countschedulesfortoday$today_sql="SELECTCOUNT(*)ascountFROMjadwalWHEREtanggal=?ANDis_deleted=false";$today_stmt=$pdo->prepare($today_sql);$today_stmt->execute([$today]);$today_count=$today_stmt->fetch()['count'];/Countschedulesfornext7days$week_sql="SELECTCOUNT(*)ascountFROMjadwalWHEREtanggalBETWEEN?AND?ANDis_deleted=false";$week_stmt=$pdo->prepare($week_sql);$week_stmt->execute([$today,$week_end]);$week_count=$week_stmt->fetch()['count'];/Ifjadwaltabledoesn'texistorhasnodata,returndefaultsif($today_count===false)$today_count=0;if($week_count===false)$week_count=0;}catch(Exception$e){/Ifjadwaltabledoesn'texist,usedefaultvalues$today_count=0;$week_count=0;}echojson_encode('\1\'=>\2,'note'=>'Scheduledatanotavailable-usingdefaultvalues'],'message'=>"Schedulestatisticsretrievedsuccessfully"],JSON_PRETTY_PRINT);break;default:thrownewException("Invalidaction:$action");}}catch(Exception$e){echojson_encode('\1\'=>\2],JSON_PRETTY_PRINT);}?>
