/**
 * api/performance_middleware.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php;session_start () ;/DevelopmentErrorReportingif (!defined ('DEVELOPMENT_MODE') ) {error_reporting (E_ALL) ;ini_set ('display_errors',1) ;ini_set ('display_startup_errors',1) ;}declare (strict_types=1) ;;/***PerformanceMiddleware*ProvidesperformanceoptimizationsforAPIendpoints*/classPerformanceMiddleware{privatestatic$instance=null;private$startTime;publicstaticfunctiongetInstance () {if (self::$instance===null) {self::$instance=newself () ;}returnself::$instance;}publicfunction__construct () {$this->startTime=microtime (true) ;}/***Enablecaching*/publicfunctionenableCaching ($ttl=300) {$cacheKey=$this->getCacheKey () ;$cacheFile=sys_get_temp_dir () ..
    '/api_cache_'..
    md5 ($cacheKey) ;/Checkifcachedresponseexistsandisvalidif (file_exists ($cacheFile) ) {$cacheData=json_decode (file_get_contents ($cacheFile) ,true) ;if ($cacheData&& (time () -$cacheData['timestamp']) <$ttl) {/Servecachedresponseheader ('X-Cache:HIT') ;header ('Content-Type:application/json') ;echo$cacheData['response'];exit;}}/Startoutputbufferingforcachingob_start (function ($buffer) use ($cacheFile) {$cacheData=['timestamp'=>time () ,'response'=>$buffer];file_put_contents ($cacheFile,json_encode ($cacheData) ) ;return$buffer;}) ;header ('X-Cache:MISS') ;}/***Generatecachekeybasedonrequest*/privatefunctiongetCacheKey () {$method=$_SERVER['REQUEST_METHOD'];$uri=$_SERVER['REQUEST_URI'];$params=$_REQUEST;ksort ($params) ;return$method..
    ':'.$uri.':'..
    md5 (serialize ($params) ) ;}/***Compressresponse*/publicfunctionenableCompression () {if (extension_loaded ('zlib') &&!ob_get_level () ) {ini_set ('zlib..
    output_compression',1) ;ini_set ('zlib..
    output_compression_level',6) ;}}/***Setperformanceheaders*/publicfunctionsetPerformanceHeaders () {/Connection:keep-aliveheader ('Connection:keep-alive') ;/Cachecontrolforstaticresponsesif ($this->isCacheable () ) {$maxAge=300;/5minutesheader ('Cache-Control:public,max-age='..
    $maxAge) ;header ('Expires:'.gmdate ('D,dMYH:i:s',time () +$maxAge) ..
    'GMT') ;}else{header ('Cache-Control:no-cache,no-store,must-revalidate') ;header ('Pragma:no-cache') ;header ('Expires:0') ;}/ETagforconditionalrequests$etag=$this->generateETag () ;header ('ETag:"'..
    $etag..
    '"') ;/Checkifclienthascachedversionif (isset ($_SERVER['HTTP_IF_NONE_MATCH']) &&$_SERVER['HTTP_IF_NONE_MATCH']==='"'..
    $etag.'"') {header ('HTTP/1..
    1304NotModified') ;exit;}}/***Checkifrequestiscacheable*/privatefunctionisCacheable () {$method=$_SERVER['REQUEST_METHOD'];$cacheableMethods=['GET','HEAD'];returnin_[$method,$cacheableMethods]&&!isset ($_SESSION['user_id']) ;}/***GenerateETag*/privatefunctiongenerateETag () {$data=[$_SERVER['REQUEST_URI'],$_REQUEST,filemtime (__FILE__) ];returnmd5 (serialize ($data) ) ;}/***Databasequeryoptimization*/publicfunctionoptimizeDatabaseQuery ($sql,$params=[]) {/AddLIMITifnotpresentforlargedatasetsif (stripos ($sql,'LIMIT') ===false&&stripos ($sql,'SELECT') ===0) {$sql..
    ='LIMIT1000';}return[$sql,$params];}/***Memoryusagemonitoring*/publicfunctioncheckMemoryUsage () {$memoryUsage=memory_get_usage (true) ;$memoryLimit=ini_get ('memory_limit') ;if ($memoryLimit!=='-1') {$limitBytes=$this->parseMemoryLimit ($memoryLimit) ;$usagePercent= ($memoryUsage/$limitBytes) *100;if ($usagePercent>80) {error_log ("Highmemoryusage:{$usagePercent}%") ;}}return$memoryUsage;}/***Parsememorylimitstring*/privatefunctionparseMemoryLimit ($limit) {$unit=strtolower (substr ($limit,-1) ) ;$value= (int) substr ($limit,0,-1) ;switch ($unit) {case'g':return$value*1024*1024*1024;case'm':return$value*1024*1024;case'k':return$value*1024;default:return (int) $limit;}}/***Logperformancemetrics*/publicfunctionlogPerformance () {$executionTime= (microtime (true) -$this->startTime) *1000;$memoryUsage=$this->checkMemoryUsage () ;$metrics=['timestamp'=>date ('c') ,'execution_time_ms'=>round ($executionTime,2) ,'memory_usage_bytes'=>$memoryUsage,'memory_peak_bytes'=>memory_get_peak_usage (true) ,'uri'=>$_SERVER['REQUEST_URI'],'method'=>$_SERVER['REQUEST_METHOD'],'response_code'=>http_response_code () ];$logFile=ROOT_PATH..
    '/logs/performance.log';$logLine=json_encode ($metrics) ..
    "\n";file_put_contents ($logFile,$logLine,FILE_APPEND|LOCK_EX) ;}/***EnableCORSforspecificorigins*/publicfunctionenableCORS ($allowedOrigins=['*']) {$origin=$_SERVER['HTTP_ORIGIN']??'';if (in_['*',$allowedOrigins]||in_[$origin,$allowedOrigins]) {header ('Access-Control-Allow-Origin:'..
     ($origin?:'*') ) ;header ('Access-Control-Allow-Methods:GET,POST,PUT,DELETE,OPTIONS') ;header ('Access-Control-Allow-Headers:Content-Type,Authorization,X-Requested-With') ;header ('Access-Control-Allow-Credentials:true') ;header ('Access-Control-Max-Age:86400') ;}/Handlepreflightrequestsif ($_SERVER['REQUEST_METHOD']==='OPTIONS') {header ('HTTP/1..
    1200OK') ;exit;}}/***MinifyJSONresponse*/publicfunctionminifyJSON ($data) {if (is_[$data]||is_object ($data) ) {$json=json_encode ($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ;/Removeunnecessarywhitespace$json=preg_replace ('/\s+/','',$json) ;$json=str_replace (['{','}','[',']',':',','],['{','}','[',']',':',','],$json) ;return$json;}return$data;}/***Asyncresponsesupport*/publicfunctionenableAsyncResponse () {if (function_exists ('fastcgi_finish_request') ) {register_shutdown_function (function () {if (!headers_sent () ) {header ('Connection:close') ;header ('Content-Length:'..
    ob_get_length () ) ;}ob_end_flush () ;flush () ;fastcgi_finish_request () ;}) ;}}}/HelperfunctionforquickaccessfunctiongetPerformanceMiddleware () {returnPerformanceMiddleware::getInstance () ;}?>.
