/**
 * api/personil_detail.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php/DevelopmentErrorReportingif(!defined('DEVELOPMENT_MODE')){error_reporting(E_ALL);ini_set('display_errors',1);ini_set('display_startup_errors',1);}declare(strict_types=1);session_start();require_once__DIR__.'/../core/config.php';/Checkauthenticationif(!isset($_SESSION['logged_in'])||$_SESSION['logged_in']!==true){header('Content-Type:application/json');echojson_encode(['success'=>false,'message'=>'Unauthorized']);exit;}/Setheadersheader("Content-Type:application/json;charset=UTF-8");try{/Databaseconnectionusingconfigconstants$dsn="mysql:host=".DB_HOST.";dbname=".DB_NAME.";unix_socket=/opt/lampp/var/mysql/mysql.sock";$pdo=newPDO($dsn,DB_USER,DB_PASS);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);/GetIDfromparameter$id=isset(filter_input($_GET===\$_GET?INPUT_GET:($_GET===\$_POST?INPUT_POST:INPUT_REQUEST),'id',FILTER_DEFAULT))?(int)filter_input($_GET===\$_GET?INPUT_GET:($_GET===\$_POST?INPUT_POST:INPUT_REQUEST),'id',FILTER_DEFAULT):null;if(!$id){thrownewException("IDparameterisrequired");}/Querypersonildata$sql="SELECTp.id,p.nama,p.nrp,p.JK,p.status_ket,p.tanggal_lahir,pg.nama_pangkat,pg.singkatan,j.nama_jabatan,b.nama_bagian,u.nama_unsur,mjp.kategoriasstatus_kepegawaianFROMpersonilpLEFTJOINpangkatpgONp.id_pangkat=pg.idLEFTJOINjabatanjONp.id_jabatan=j.idLEFTJOINbagianbONp.id_bagian=b.idLEFTJOINunsuruONp.id_unsur=u.idLEFTJOINmaster_jenis_pegawaimjpONp.id_jenis_pegawai=mjp.idWHEREp.id=?ANDp.is_deleted=falseANDp.is_active=trueLIMIT1";$stmt=$pdo->prepare($sql);$stmt->execute([$id]);$personil=$stmt->fetch();if(!$personil){thrownewException("Personilnotfound");}/ReturnJSONresponseechojson_encode(['success'=>true,'data'=>['id'=>$personil['id'],'nama'=>$personil['nama'],'nrp'=>$personil['nrp'],'JK'=>$personil['JK'],'status_ket'=>$personil['status_ket'],'tanggal_lahir'=>$personil['tanggal_lahir'],'pangkat'=>$personil['singkatan']?:$personil['nama_pangkat'],'jabatan'=>$personil['nama_jabatan'],'bagian'=>$personil['nama_bagian'],'unsur'=>$personil['nama_unsur'],'status_kepegawaian'=>$personil['status_kepegawaian']]]);}catch(Exception$e){echojson_encode(['success'=>false,'message'=>$e->getMessage()]);}?>
