/**
 * api/simple.php
 *
 * @package SPRIN
 * @author Development Team
 * @since 1.0.0
 */

<?php/DevelopmentErrorReportingif(!defined('DEVELOPMENT_MODE')){error_reporting(E_ALL);ini_set('display_errors',1);ini_set('display_startup_errors',1);}declare(strict_types=1);/***SimpleAPIforbagiandata-StandardizedVersion*//SetJSONcontenttypefirstheader('Content-Type:application/json;charset=UTF-8');require_once__DIR__.'/../core/config.php';require_once__DIR__.'/../core/Database.php';/Disableerrordisplayinproductionif(ENVIRONMENT!=='development'){error_reporting(0);ini_set('display_errors',0);}try{/UseDatabasesingleton$db=Database::getInstance();$pdo=$db->getConnection();/Getbagiandatawithpersonilcount$sql="SELECTb.id,b.kode_bagian,b.nama_bagian,b.id_unsur,b.deskripsi,(SELECTCOUNT(*)FROMpersonilpWHEREp.id_bagian=b.idANDp.is_deleted=falseANDp.is_active=true)aspersonil_count,(SELECTp.namaFROMpersonilpJOINbagian_pimpinanbpONp.id=bp.personil_idWHEREbp.bagian_id=b.idANDbp.tanggal_selesaiISnullLIMIT1)askepalaFROMbagianbWHEREb.is_active=1ORDERBYb.nama_bagian";$stmt=$pdo->prepare($sql);$stmt->execute();$bagianData=$stmt->fetchAll(PDO::FETCH_ASSOC);/Addpersonildetailsforeachbagianforforeach($bagianDataas&$bagian){$personilSql="SELECTp.id,p.nama,p.nrp,pg.singkatanaspangkat,pg.level_pangkat,j.nama_jabatanFROMpersonilpLEFTJOINpangkatpgONp.id_pangkat=pg.idLEFTJOINjabatanjONp.id_jabatan=j.idWHEREp.id_bagian=?ANDp.is_deleted=falseANDp.is_active=trueORDERBYCASEWHENpg.level_pangkatISnullTHEN999999ELSEpg.level_pangkatENDASC,CASEWHENp.nrpREGEXP'^[0-9]{8}'THENCASEWHENSUBSTRING(p.nrp,1,1)='0'THENCONCAT('20',SUBSTRING(p.nrp,1,4))ELSECONCAT('19',SUBSTRING(p.nrp,1,4))ENDWHENp.nrpREGEXP'^[0-9]{9}'THENCONCAT('19',SUBSTRING(p.nrp,1,6))ELSE'99999999'ENDASC,p.namaASC";$personilStmt=$pdo->prepare($personilSql);$personilStmt->execute([$bagian['id']]);$bagian['personil']=$personilStmt->fetchAll(PDO::FETCH_ASSOC);}/Returnsuccessresponse/SendJSONresponseechojson_encode(['success'=>true,'message'=>"Retrieved".count($bagianData)."bagianrecords",'data'=>['bagian'=>$bagianData,'total_bagian'=>count($bagianData)],'timestamp'=>date('c')]);}catch(Exception$e){header('Content-Type:application/json;charset=UTF-8');if(ENVIRONMENT==='development'){echojson_encode(['success'=>false,'message'=>'Databaseerror:'.$e->getMessage(),'timestamp'=>date('c')]);}else{echojson_encode(['success'=>false,'message'=>'Failedtoretrievebagiandata','timestamp'=>date('c')]);}}?>
